services:
  - type: web
    name: lostfoundpk-backend
    runtime: python
    rootDir: LostFoundPK-backend
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    healthCheckPath: /health
    envVars:
      - key: MONGO_URI
        sync: false
      - key: MONGO_DB_NAME
        value: LostFoundPK
      - key: JWT_SECRET_KEY
        generateValue: true
      - key: SENDGRID_API_KEY
        sync: false
      - key: EMAIL_FROM
        value: talha.abid.joyia@gmail.com
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
      - key: PYTHON_VERSION
        value: 3.12.0
